### ISSUE TITLE
Ask the user the name of the cpp file which will be created as command line argument

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/CP-setup#2]
CURRENT SCENARIO :- 
The script makes a file named `test.cpp` in a separate folder named `cp` just a directory outside the repo.
in short it makes file `../cp/test.cpp`

EXPECTED SCENARIO :- 
The user sent the name of the file via the command line arguments and the file should be created with that name
- if the file name already exist then create a file with a number proceeding it `<file_name>_1.cpp` or `<file_name>_2.cpp` or `<file_name>_3.cpp` and so on

**Comment by OrangoMango** [comment]
I will try to do it

**Comment by Arsenic-ATG** [comment]
ok @OrangoMango, I am assigning you this issue 🙂

**Comment by OrangoMango** [comment]
Can I attach a pull request to the comment?

**Comment by OrangoMango** [comment]
#5 I changed the setup.py file.
