### ISSUE TITLE
Add initial lines of code to the generated cpp file

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/CP-setup#3]
## Present Scenario : - 
The target file which gets created have almost nothing prewritten in it ( just a blank file with a comment which marks the start of the file)

## Expected Scenario : - 
generated file should already contain the boilerplate code containing most of the required header, and frequently used user defined functions ( like taking input from an array)

## How I would approach it ( you may use your way ) : -
1. create a file(text/cpp) contains the reference code
2. copy the contents of that file to the file generated by the script

**Comment by OrangoMango** [comment]
Sorry but I can't program C++

**Comment by Arsenic-ATG** [comment]
> Sorry but I can't program C++

@OrangoMango  that should not be a problem, If you want I can create a boilerplate cpp file and all you have to do is to copy the contents of that file ( like you would do with a text file ) and paste them in file generated by the script

**Comment by OrangoMango** [comment]
I can try

**Comment by Arsenic-ATG** [comment]
@OrangoMango ok 🙂

let me create a `reference.cpp` file in the repo and then all you have to do is to make sure that when the script runs, it copies all the content of the `reference.cpp` to the file created by script.

update : reference.cpp has been created

**Comment by OrangoMango** [comment]
Ok
